language: php
php:
  - 5.3.2
  - 5.3
  - 5.4

before_script:
  - pyrus install pear.php.net/PEAR
  - phpenv rehash
  - php onion.phar -d bundle
  - ./scripts/compile.sh
  - php onion.phar -d build --pear

script: phpunit
